############# markdown #############
[[plugins]]
repo = 'plasticboy/vim-markdown'
repo = 'previm/previm'
on_ft = ['markdown']


############# edit #############
# replace preview
[[plugins]]
repo = 'markonm/traces.vim'


############# rest client #############
[[plugins]]
repo = 'baverman/vial'

[[plugins]]
repo = 'baverman/vial-http'


############# docker #############
[[plugins]]
repo = 'skanehira/docker.vim'


############# vim #############
[[plugins]]
repo = "puremourning/vimspector"
on_ft = ["python", "javascript", "typescript"]
build = "./install_gadget.py --enable-python --force-enable-node"


############# go #############
[[plugins]]
repo = "mattn/vim-goimports"
