############# vim #############
[[plugins]]
repo = "puremourning/vimspector"
on_ft = ["python", "javascript", "typescript"]
build = "./install_gadget.py --enable-python --force-enable-node"


############# go #############
[[plugins]]
repo = "mattn/vim-goimports"
